In [1]:
import grrmlib as gl

gl.__version__

'0.1.0'

In [2]:
eqs = gl.read_eq_list("td_c1_193_SCAFIR6_EQ_list.log")
pts = gl.read_pt_list("td_c1_193_SCAFIR6_PT_list.log")

In [3]:
rpn = gl.ReactionPathNetwork(eqs=eqs, pts=pts)
rpn = rpn.remove_eq("??")

In [4]:
grpn = rpn.cluster(gl.is_identical)

In [5]:
writer = gl.GaussianInputWriter()

# 0. Benzene complex

In [6]:
eqs0 = (
    eqs
    .filter(lambda eq: 2.25 < eq.get_distance(1, 25) < 2.65)
    .filter(lambda eq: eq.get_distance(13, 25) > 2.60)
    .filter(lambda eq: eq.get_distance(16, 25) > 2.60)
    .filter(lambda eq: eq.get_distance(7, 37) > 1.10)
    .filter(lambda eq: eq.get_distance(7, 35) > 1.10)
    .filter(lambda eq: eq.get_distance(1, 13) > 1.60)
    .filter(lambda eq: eq.get_distance(14, 25) > 1.60)
    .filter(lambda eq: 3.50 < eq.get_distance(35, 42) < 4.50)
    .filter(lambda eq: eq.get_distance(52, 53) < 1.20)
)

In [7]:
len(eqs0)

103

In [8]:
eqs0_min = eqs0.smallest("scfenergy")

In [9]:
eqs0_min.name

308

In [10]:
writer.write(eqs0_min, f"EQ{eqs0_min.name}.com", overwrite=True)

PosixPath('EQ308.com')

# 1. C–H activation complex

In [11]:
eqs1 = (
    eqs
    .filter(lambda eq: eq.get_distance(1, 25) < 2.25)
    .filter(lambda eq: eq.get_distance(13, 25) > 2.60)
    .filter(lambda eq: eq.get_distance(16, 25) > 2.60)
    .filter(lambda eq: eq.get_distance(7, 37) < 1.10)
    .filter(lambda eq: eq.get_distance(7, 35) > 1.10)
    .filter(lambda eq: eq.get_distance(1, 13) > 1.60)
    .filter(lambda eq: eq.get_distance(14, 25) > 1.60)
)

In [12]:
len(eqs1)

200

In [13]:
eqs1_min = eqs1.smallest("scfenergy")

In [14]:
eqs1_min.name

757

In [15]:
writer.write(eqs1_min, f"EQ{eqs1_min.name}.com", overwrite=True)

PosixPath('EQ757.com')

In [16]:
pts01 = rpn.pts_between(308, 757)

In [17]:
len(pts01)

7

In [18]:
pts01_min = pts01.smallest("scfenergy")

In [19]:
pts01_min.name

1952

In [20]:
writer.write(pts01_min, f"PT{pts01_min.name}.com", overwrite=True)

PosixPath('PT1952.com')

# 2. Olefin coordination complex

In [21]:
eqs2 = (
    eqs
    .filter(lambda eq: eq.get_distance(1, 25) < 2.25)
    .filter(lambda eq: 2.10 < eq.get_distance(13, 25) < 2.60)
    .filter(lambda eq: 2.10 < eq.get_distance(16, 25) < 2.60)
    .filter(lambda eq: eq.get_distance(7, 37) < 1.10)
    .filter(lambda eq: eq.get_distance(7, 35) > 1.10)
    .filter(lambda eq: eq.get_distance(1, 13) > 1.60)
    .filter(lambda eq: eq.get_distance(14, 25) > 1.60)
)

In [22]:
len(eqs2)

312

In [23]:
eqs2_min = eqs2.smallest("scfenergy")

In [24]:
eqs2_min.name

1769

In [25]:
writer.write(eqs2_min, f"EQ{eqs2_min.name}.com", overwrite=True)

PosixPath('EQ1769.com')

In [26]:
pts12 = rpn.pts_between(757, 1769)

In [27]:
len(pts12)

0

In [28]:
grpn.group_of_eq(757)

46

In [29]:
grpn.group_of_eq(1769)

157

In [30]:
pts12 = grpn.pts_between(46, 157)

In [31]:
len(pts12)

38

In [32]:
pts12_min = pts12.smallest("scfenergy")

In [33]:
pts12_min.name

1685

In [34]:
writer.write(pts12_min, f"PT{pts12_min.name}.com", overwrite=True)

PosixPath('PT1685.com')

# 3. Proton transfer complex

In [35]:
eqs3 = (
    eqs
    .filter(lambda eq: eq.get_distance(1, 25) < 2.25)
    .filter(lambda eq: 2.10 < eq.get_distance(13, 25) < 2.60)
    .filter(lambda eq: 2.10 < eq.get_distance(16, 25) < 2.60)
    .filter(lambda eq: eq.get_distance(7, 37) > 1.10)
    .filter(lambda eq: eq.get_distance(7, 35) < 1.10)
    .filter(lambda eq: eq.get_distance(1, 13) > 1.60)
    .filter(lambda eq: eq.get_distance(14, 25) > 1.60)
)

In [36]:
len(eqs3)

499

In [37]:
eqs3_min = eqs3.smallest("scfenergy")

In [38]:
eqs3_min.name

2177

In [39]:
writer.write(eqs3_min, f"EQ{eqs3_min.name}.com", overwrite=True)

PosixPath('EQ2177.com')

In [40]:
pts23 = rpn.pts_between(1769, 2177)

In [41]:
len(pts23)

0

In [42]:
grpn.group_of_eq(2177)

324

In [43]:
pts23 = grpn.pts_between(157, 324)

In [44]:
len(pts23)

0

In [45]:
import networkx as nx

list(nx.all_shortest_paths(grpn, 157, 324))

[[157, 252, 324], [157, 275, 324]]

In [46]:
pts23_0 = grpn.pts_between(157, 252)

In [47]:
len(pts23_0)

25

In [48]:
pts23_0_min = pts23_0.smallest("scfenergy")

In [49]:
pts23_0_min.name

4068

In [50]:
writer.write(pts23_0_min, f"PT{pts23_0_min.name}.com", overwrite=True)

PosixPath('PT4068.com')

In [51]:
pts23_1 = grpn.pts_between(252, 324)

In [52]:
len(pts23_1)

1

In [53]:
pts23_1_min = pts23_1.smallest("scfenergy")

In [54]:
pts23_1_min.name

3836

In [55]:
writer.write(pts23_1_min, f"PT{pts23_1_min.name}.com", overwrite=True)

PosixPath('PT3836.com')

In [56]:
pts23_3 = grpn.pts_between(157, 275)

In [57]:
len(pts23_3)

6

In [58]:
pts23_3_min = pts23_3.smallest("scfenergy")

In [59]:
pts23_3_min.name

3358

In [60]:
writer.write(pts23_3_min, f"PT{pts23_3_min.name}.com", overwrite=True)

PosixPath('PT3358.com')

In [61]:
pts23_4 = grpn.pts_between(275, 324)

In [62]:
len(pts23_4)

72

In [63]:
pts23_4_min = pts23_4.smallest("scfenergy")

In [64]:
pts23_4_min.name

5879

In [65]:
writer.write(pts23_4_min, f"PT{pts23_4_min.name}.com", overwrite=True)

PosixPath('PT5879.com')

In [66]:
eqs23_0 = grpn.eqs_of_group(252)

In [67]:
len(eqs23_0)

43

In [68]:
eqs23_0_min = eqs23_0.smallest("scfenergy")

In [69]:
eqs23_0_min.name

2014

In [70]:
writer.write(eqs23_0_min, f"EQ{eqs23_0_min.name}.com", overwrite=True)

PosixPath('EQ2014.com')

In [71]:
eqs23_1 = grpn.eqs_of_group(275)

In [72]:
len(eqs23_1)

137

In [73]:
eqs23_1_min = eqs23_1.smallest("scfenergy")

In [74]:
eqs23_1_min.name

2567

In [75]:
writer.write(eqs23_1_min, f"EQ{eqs23_1_min.name}.com", overwrite=True)

PosixPath('EQ2567.com')

# 4. Carbopalladation complex

In [76]:
eqs4 = (
    eqs
    .filter(lambda eq: eq.get_distance(1, 25) > 2.25)
    .filter(lambda eq: eq.get_distance(13, 25) > 2.60)
    .filter(lambda eq: eq.get_distance(16, 25) < 2.10)
    .filter(lambda eq: eq.get_distance(7, 37) > 1.10)
    .filter(lambda eq: eq.get_distance(7, 35) < 1.10)
    .filter(lambda eq: eq.get_distance(1, 13) < 1.60)
    .filter(lambda eq: eq.get_distance(14, 25) > 1.60)
)

In [77]:
len(eqs4)

334

In [78]:
eqs4_min = eqs4.smallest("scfenergy")

In [79]:
eqs4_min.name

3791

In [80]:
writer.write(eqs4_min, f"EQ{eqs4_min.name}.com", overwrite=True)

PosixPath('EQ3791.com')

In [81]:
pts34 = rpn.pts_between(2711, 3791)

In [82]:
len(pts34)

0

In [83]:
grpn.group_of_eq(3791)

551

In [84]:
pts34 = grpn.pts_between(324, 551)

In [85]:
len(pts34)

0

In [86]:
paths34 = list(nx.all_shortest_paths(grpn, 324, 551))

In [87]:
paths34

[[324, 275, 442, 551],
 [324, 357, 442, 551],
 [324, 465, 442, 551],
 [324, 357, 519, 551]]

In [88]:
paths34_energies = [
    [
        grpn.pts_between(u, v).smallest("scfenergy").scfenergy
        for u, v in zip(path, path[1:])
    ]
    for path in paths34
]

In [89]:
paths34_energies

[[-1004.45328169788, -1004.434246781242, -1004.437676477578],
 [-1004.435690691884, -1004.457428658336, -1004.437676477578],
 [-1004.42725389787, -1004.451892856649, -1004.437676477578],
 [-1004.435690691884, -1004.424412647384, -1004.469373082363]]

-> path [324, 357, 442, 551] has the lowest transition state

In [90]:
pts34_0 = grpn.pts_between(324, 357)

In [91]:
len(pts34_0)

8

In [92]:
pts34_0_min = pts34_0.smallest("scfenergy")

In [93]:
pts34_0_min.name

5992

In [94]:
writer.write(pts34_0_min, f"PT{pts34_0_min.name}.com", overwrite=True)

PosixPath('PT5992.com')

In [95]:
pts34_1 = grpn.pts_between(357, 442)

In [96]:
len(pts34_1)

18

In [97]:
pts34_1_min = pts34_1.smallest("scfenergy")

In [98]:
pts34_1_min.name

6133

In [99]:
writer.write(pts34_1_min, f"PT{pts34_1_min.name}.com", overwrite=True)

PosixPath('PT6133.com')

In [100]:
pts34_2 = grpn.pts_between(442, 551)

In [101]:
len(pts34_2)

1

In [102]:
pts34_2_min = pts34_2.smallest("scfenergy")

In [103]:
pts34_2_min.name

6768

In [104]:
writer.write(pts34_2_min, f"PT{pts34_2_min.name}.com", overwrite=True)

PosixPath('PT6768.com')

In [105]:
eqs34_0 = grpn.eqs_of_group(357)

In [106]:
len(eqs34_0)

22

In [107]:
eqs34_0_min = eqs34_0.smallest("scfenergy")

In [108]:
eqs34_0_min.name

2746

In [109]:
writer.write(eqs34_0_min, f"EQ{eqs34_0_min.name}.com", overwrite=True)

PosixPath('EQ2746.com')

In [110]:
eqs34_1 = grpn.eqs_of_group(442)

In [111]:
len(eqs34_1)

42

In [112]:
eqs34_1_min = eqs34_1.smallest("scfenergy")

In [113]:
eqs34_1_min.name

2692

In [114]:
writer.write(eqs34_1_min, f"EQ{eqs34_1_min.name}.com", overwrite=True)

PosixPath('EQ2692.com')

# 5. Product complex

In [115]:
eqs5 = (
    eqs
    .filter(lambda eq: eq.get_distance(1, 25) > 2.25)
    .filter(lambda eq: 2.10 < eq.get_distance(13, 25) < 2.60)
    .filter(lambda eq: 2.10 < eq.get_distance(16, 25) < 2.60)
    .filter(lambda eq: eq.get_distance(7, 37) > 1.10)
    .filter(lambda eq: eq.get_distance(7, 35) < 1.10)
    .filter(lambda eq: eq.get_distance(1, 13) < 1.60)
    .filter(lambda eq: eq.get_distance(14, 25) < 1.60)
)

In [116]:
len(eqs5)

152

In [117]:
eqs5_min = eqs5.smallest("scfenergy")

In [118]:
eqs5_min.name

3196

In [119]:
writer.write(eqs5_min, f"EQ{eqs5_min.name}.com", overwrite=True)

PosixPath('EQ3196.com')

In [120]:
pts45 = rpn.pts_between(3791, 3196)

In [121]:
len(pts45)

0

In [122]:
grpn.group_of_eq(3196)

494

In [123]:
pts45 = grpn.pts_between(551, 494)

In [124]:
len(pts45)

0

In [125]:
paths45 = list(nx.all_shortest_paths(grpn, 551, 494))

In [126]:
paths45

[[551, 519, 469, 494],
 [551, 464, 469, 494],
 [551, 504, 469, 494],
 [551, 520, 469, 494],
 [551, 505, 469, 494],
 [551, 519, 357, 494],
 [551, 442, 357, 494],
 [551, 519, 601, 494],
 [551, 519, 507, 494]]

In [127]:
paths45_energies = [
    [
        grpn.pts_between(u, v).smallest("scfenergy").scfenergy
        for u, v in zip(path, path[1:])
    ]
    for path in paths45
]

In [128]:
paths45_energies

[[-1004.469373082363, -1004.446736305908, -1004.430865164457],
 [-1004.468449730746, -1004.449171808157, -1004.430865164457],
 [-1004.443189952098, -1004.421854826252, -1004.430865164457],
 [-1004.442381582628, -1004.42365421656, -1004.430865164457],
 [-1004.420808659228, -1004.446744166918, -1004.430865164457],
 [-1004.469373082363, -1004.424412647384, -1004.445129492283],
 [-1004.437676477578, -1004.457428658336, -1004.445129492283],
 [-1004.469373082363, -1004.333215248036, -1004.432309776477],
 [-1004.469373082363, -1004.436109287352, -1004.45845476253]]

-> path [551, 442, 357, 494] has the lowest transition state

In [129]:
pts45 = grpn.pts_between(357, 494)

In [130]:
len(pts45)

2

In [131]:
pts45_min = pts45.smallest("scfenergy")

In [132]:
pts45_min.name

6292

In [133]:
writer.write(pts45_min, f"PT{pts45_min.name}.com", overwrite=True)

PosixPath('PT6292.com')